spring:
  application:
    name: assignment


  datasource:
    url: jdbc:mysql://localhost:3306/assignment
    username: sopt
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true

security:
  jwt:
    secret: seopsopt-fighting
    access-token-expires-in-seconds: 1800     # 30분
    refresh-token-expires-in-seconds: 1209600 # 2주

oauth:
  kakao:
    rest-api-key: ${KAKAO_REST_API_KEY}
    client-secret: ${KAKAO_CLIENT_SECRET:}
    redirect-uri: http://localhost:8080/api/v1/oauth2/kakao/callback
